name: "PPO Actor Critic style, Crawler"
program: scripts/sweep_crawler_ac_ppo.py
method: bayes
metric:
  name: reward
  goal: maximize
parameters:
  discount_rate:
    values: [.99, 0.9, 0.8]
  epsilon:
    values: [.01, 0.1]
  epsilon_decay:
    values: [.99, 0.9995, .8]
  beta:
    values: [.1, 0.01]
  beta_deay:
    values: [.99, .9995, 0.8]
  learning_rate:
    min: 0.00001
    max: 0.01
  SGD_epoch:
    values: [4]
  n_iterations:
    values: [2000]
  max_t:
    values: [1024]
  gae_lambda:
    values: [0.995, 0.9, 0.8, 0.5]