name: "PPO Actor Critic style, Crawler"
program: sweep_crawler_ac_ppo.py
method: bayes
metric:
  name: reward
  goal: maximize
parameters:
  discount_rate:
    min: 0.5
    max: 1.0
  epsilon:
    min: 0.0001
    max: 0.1
  epsilon_decay:
    min: 0.5
    max: 1.0
  beta:
    min: 0.0001
    max: 0.1
  beta_deay:
    min: 0.5
    max: 1.0
  learning_rate:
    min: 0.00001
    max: 0.1
  SGD_epoch:
    values: [4, 12]
  n_iterations:
    values: [2000]
  max_t:
    values: [1024]
  gae_lambda:
    min: 0.5
    max: 1.0