version: '2.3'
services:
    train_reacher:
        build: .
        volumes:
            - .:/app
        command: python main.py
    sweep_reacher:
        build: .
        runtime: nvidia
        volumes:
            - .:/app
        command: >
            bash -c "wandb login bda330f5b627e9dc2184d317b1ab465c7a79b991
            && wandb agent --count 4 mse-deep-learning/p2_continuous-control/rfq0byxn"
