version: '2.3'
services:
    train_reacher:
        build: .
        volumes:
            - .:/app
        command: python main.py
    sweep_reacher:
        build: .
        runtime: nvidia
        volumes:
            - .:/app
        command: >
            bash -c "wandb login <API-KEY>
            && wandb agent --count 4 <RUN-ID>"
